#!/usr/bin/env bash
# ============================================================================
# run_Pipeline.sh — Single entry point for the SkiCycleRun pipeline.
#
# NO preamble scripts required. All paths and settings are read from:
#   config/pipeline_config.json
#
# Usage:
#   ./run_Pipeline.sh                          # run all default stages
#   ./run_Pipeline.sh --stages lora_processing
#   ./run_Pipeline.sh --lora_processing        # shorthand for --stages lora_processing
#   ./run_Pipeline.sh --stages lora_processing post_lora_watermarking s3_deployment
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# ── Python interpreter ────────────────────────────────────────────────────────
# Prefer the project-pinned pyenv interpreter directly so the runner still works
# even when pyenv shims are not active in the current shell.
if command -v pyenv >/dev/null 2>&1; then
  if PYENV_PYTHON="$(pyenv which python3 2>/dev/null)"; then
    PYTHON_CMD="$PYENV_PYTHON"
  elif PYENV_PYTHON="$(pyenv which python 2>/dev/null)"; then
    PYTHON_CMD="$PYENV_PYTHON"
  else
    PYTHON_CMD=""
  fi
else
  PYTHON_CMD=""
fi

if [[ -z "$PYTHON_CMD" ]]; then
  if command -v python3 >/dev/null 2>&1; then
    PYTHON_CMD="$(command -v python3)"
  elif command -v python >/dev/null 2>&1; then
    PYTHON_CMD="$(command -v python)"
  else
    printf '❌  No python3 or python found in PATH. Install via pyenv or system package manager.\n' >&2
    exit 1
  fi
fi

# ── Check .env exists (generated by run_SetupEnv.sh) ─────────────────────────
if [[ ! -f "$SCRIPT_DIR/.env" ]]; then
  printf '⚠️  No .env found. Run ./run_SetupEnv.sh --profile <profile> first.\n' >&2
fi

# ── PyTorch / MPS init-time env vars ─────────────────────────────────────────
# These must be in the shell environment BEFORE Python starts — PyTorch and
# tokenizers read them once at first import, before any os.environ assignment
# inside Python can take effect.
#
# PYTORCH_ENABLE_MPS_FALLBACK : route unsupported Metal ops to CPU (required for FLUX)
# PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0 : disable the default 50 % MPS memory cap
# PYTORCH_MPS_LOW_WATERMARK_RATIO=0.7  : set low-watermark trim threshold to 70 %
# OMP_NUM_THREADS=1              : stop OpenMP spawning CPU threads that fight MPS
# TOKENIZERS_PARALLELISM=false   : avoid tokenizer fork-safety warnings under MPS
export PYTORCH_ENABLE_MPS_FALLBACK=1
export PYTORCH_MPS_HIGH_WATERMARK_RATIO=0.0
export PYTORCH_MPS_LOW_WATERMARK_RATIO=0.7
export OMP_NUM_THREADS=1
export TOKENIZERS_PARALLELISM=false

# ── Stage shorthand normalization ────────────────────────────────────────────
# Allow ergonomic one-flag stage calls like:
#   ./run_Pipeline.sh --lora_processing
# This maps to:
#   ./run_Pipeline.sh --stages lora_processing
normalized_args=()
shortcut_stages=()
has_stages_flag=0

for arg in "$@"; do
  case "$arg" in
    --stages|-stages)
      has_stages_flag=1
      normalized_args+=("$arg")
      ;;
    --export|--cleanup|--metadata_extraction|--llm_image_analysis|--preprocessing|--lora_processing|--post_lora_watermarking|--travel_log_generation|--s3_deployment)
      shortcut_stages+=("${arg#--}")
      ;;
    *)
      normalized_args+=("$arg")
      ;;
  esac
done

if [[ ${#shortcut_stages[@]} -gt 0 ]]; then
  if [[ $has_stages_flag -eq 1 ]]; then
    printf '❌  Do not mix stage shorthand flags with --stages. Use one style.\n' >&2
    exit 2
  fi
  normalized_args=(--stages "${shortcut_stages[@]}" "${normalized_args[@]}")
fi

# ── Launch ────────────────────────────────────────────────────────────────────
printf '🚀 Starting pipeline (Python: %s)\n' "$("$PYTHON_CMD" --version 2>&1)"
printf '📋 Command: %s pipeline.py' "$PYTHON_CMD"
for arg in "${normalized_args[@]}"; do
  printf ' %q' "$arg"
done
printf '\n'

if command -v caffeinate >/dev/null 2>&1; then
  exec caffeinate -dimsu "$PYTHON_CMD" pipeline.py "${normalized_args[@]}"
else
  printf '⚠️  caffeinate not found; running without sleep prevention\n'
  exec "$PYTHON_CMD" pipeline.py "${normalized_args[@]}"
fi
